---
- name: Update web, and NFS servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: Ensure wireshark is at the latest version
      ansible.builtin.yum:
        name: wireshark
        state: present

- name: Update LB and Database server
  hosts: lb, db
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Update apt repo
      ansible.builtin.apt: 
        update_cache: true

    - name: Ensure wireshark is at the latest version
      ansible.builtin.apt:
        name: wireshark
        state: present
