# mail.example.com

[nfs]
172.31.39.62 ansible_ssh_user='ec2-user'

[webservers]
172.31.3.37 ansible_ssh_user='ec2-user'
172.31.39.111 ansible_ssh_user='ec2-user'

[db]
172.31.44.12 ansible_ssh_user='ubuntu'

[lb]
172.31.37.196 ansible_ssh_user='ubuntu'

[multi:children]
nfs
webservers
db 
lb 

# Variables that will be applied to all servers
[multi:vars]
host_key_checking=false



# [nfs]
# 172.31.39.62 ansible_ssh_user='ec2-user'

# [webservers]
# 172.31.37.185 ansible_ssh_user='ec2-user'
# 172.31.39.111 ansible_ssh_user='ec2-user'

# [db]
# 172.31.44.12 ansible_ssh_user='ec2-user' 

# [lb]
# 172.31.32.249 ansible_ssh_user='ubuntu'