---
- hosts: all
- import_playbook: ../static-assignments/common.yaml
- import_playbook: ../static-assignments/common-del.yaml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml